
name: icejoywoo's blog
description: 程序员的自我修养
meta_description: "icejoywoo, blog"
safe: true
fenced_code_blocks: true

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /

author:         'icejoywoo'
authorTwitter:  'icejoywoo'
disqus_shortname: 'icejoywoo'

permalink:       /:categories/:year/:month/:day/:title.html

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
